import type { Metadata } from "next";
import { Lilita_One, Montserrat } from 'next/font/google'
import Navbar from "../components/Navbar";
import "./globals.css";

export const lilita = Lilita_One({
  weight:'400',
  subsets:['latin'],
})

export const montserrat = Montserrat({
  weight: ['700','400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.className} dark`}>
      <body className="grid align-top justify-center text-center text-[var(--secundary)] py-2 bg-[var(--primary)] dark:bg-[var(--dark-bg)] dark:text-[var(--actionHover)] transition-colors duration-300" >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
